### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by chrisdugne** [cengiz-pz/godot-ios-inapp-review-plugin#1]
Hello! thanks for providing an iOS plugin once more;

I'm using godot 4.2.2, and the install from the AssetLib to have the `iOS/plugin` files.
I have checked the plugin in both project settings and iOS export parameters.

Now building the app on XCode sends:

```
Undefined symbols for architecture arm64:
  "ClassDB::bind_methodfi(unsigned int, MethodBind*, bool, char const*, Variant const**, int)", referenced from:
      InappReviewPlugin::_bind_methods() in InappReviewPlugin.a(godot_plugin_class.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you have any tips ? 
Is there a mismatch with my godot version and then the godot headers provided in the AssetLib ?

**Comment by cengiz-pz** [comment]
Hi @chrisdugne, it sounds like you are using the release version of the plugin binary for a debug export.  If you replace the following line:

    binary="InappReviewPlugin.release.xcframework"

in your `InappReviewPlugin.gdip` file to the following

    binary="InappReviewPlugin.debug.xcframework"

your issue should be resolved.

I haven't yet tested this, but I'm told that `"InappReviewPlugin.xcframework"` will do the trick as well since Godot's export system automatically switches the binary depending on the export type.  Once I reunite with my Mac sometime next month, I'll verify and publish an update.
